services:
  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: url-shortener-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - MONGO_URI=mongodb://mongoadmin:secret@localhost:27017/?timeoutMS=5000
    depends_on:
      - redis
    restart: unless-stopped
